services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - redis
        env_file:
            - .env

    redis:
        image: "redis:latest"
        volumes:
            - ./redis-data:/data
